renderer:
  build: .
  environment:
    MAPBOX_ACCESS_TOKEN: <obtain api token at mapbox.com>
    STYLE_NAME: osm-bright
  volumes:
    - ./tile-cache:/tilelive/tiles
nginx:
  image: nginx:latest
  links:
    - renderer
  volumes_from:
    - renderer
  volumes:
    - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "8080:80"
